import type { Metadata } from "next";
import { Quantico } from "next/font/google";
import "./globals.scss";
import styles from "./layout.module.scss";
import Link from "next/link";

const quantico = Quantico({
  subsets: ["latin"],
  weight: ["400", "700"], // importante
  variable: "--font-quantico",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quantico.variable} ${quantico.variable}`}>
        <div className={styles.container}>
          <aside className={`${styles.sidebar} ${styles.box}`}>
            <nav>
              <ul>
                <li>
                  <Link href="/">About</Link>
                </li>
                <li>
                  <Link href="/education">Education</Link>
                </li>
                <li>
                  <Link href="/stack">Stack</Link>
                </li>
                <li>
                  <Link href="/skills">Skills</Link>
                </li>
                <li>
                  <Link href="/projects">Projects</Link>
                </li>
                <li>
                  <Link href="/hobbies">Hobbies</Link>
                </li>
                <li>
                  <Link href="/contact">Contact</Link>
                </li>
                <li>
                  <Link href="/faq">FAQ</Link>
                </li>
              </ul>
            </nav>
          </aside>

          <main className={`${styles.main} ${styles.box}`}>
            {children}
          </main>

          <aside className={`${styles.social} ${styles.box}`}></aside>
        </div>
      </body>
    </html>
  );
}
