import type { Metadata } from "next";
import { Quantico } from "next/font/google";
import "./globals.scss";

const quantico = Quantico({
  subsets: ["latin"],
  weight: ["400", "700"], // importante
  variable: "--font-quantico",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quantico.variable} ${quantico.variable}`}>
        {children}
      </body>
    </html>
  );
}
